name: client-push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Yarn install
        run: |
          yarn
      - name: NextJS Build
        run: |
          yarn build
